// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Optimizes video and audio quality during screen sharing based on network bandwidth and device capabilities.
 *
 * - optimizeScreenQuality - A function that handles the optimization process.
 * - OptimizeScreenQualityInput - The input type for the optimizeScreenQuality function.
 * - OptimizeScreenQualityOutput - The return type for the optimizeScreenQuality function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OptimizeScreenQualityInputSchema = z.object({
  networkBandwidth: z.string().describe('The available network bandwidth (e.g., "10 Mbps").'),
  deviceCapabilities: z.string().describe('The device capabilities (e.g., "High-end desktop with powerful GPU").'),
  currentVideoQuality: z.string().describe('The current video quality settings (e.g., "720p, 30fps").'),
  currentAudioQuality: z.string().describe('The current audio quality settings (e.g., "Stereo, 128kbps").'),
});
export type OptimizeScreenQualityInput = z.infer<typeof OptimizeScreenQualityInputSchema>;

const OptimizeScreenQualityOutputSchema = z.object({
  suggestedVideoQuality: z.string().describe('The suggested video quality settings (e.g., "1080p, 60fps").'),
  suggestedAudioQuality: z.string().describe('The suggested audio quality settings (e.g., "Stereo, 192kbps").'),
  reasoning: z.string().describe('The reasoning behind the suggested changes.'),
});
export type OptimizeScreenQualityOutput = z.infer<typeof OptimizeScreenQualityOutputSchema>;

export async function optimizeScreenQuality(input: OptimizeScreenQualityInput): Promise<OptimizeScreenQualityOutput> {
  return optimizeScreenQualityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeScreenQualityPrompt',
  input: {schema: OptimizeScreenQualityInputSchema},
  output: {schema: OptimizeScreenQualityOutputSchema},
  prompt: `You are an expert in optimizing screen sharing quality based on network conditions and device capabilities.

  Given the following information, suggest optimal video and audio quality settings for screen sharing.

  Network Bandwidth: {{{networkBandwidth}}}
  Device Capabilities: {{{deviceCapabilities}}}
  Current Video Quality: {{{currentVideoQuality}}}
  Current Audio Quality: {{{currentAudioQuality}}}

  Consider the trade-offs between quality and performance. Provide a brief explanation for your suggestions.
  Make sure that the video and audio quality output are valid and well known.
  Reasoning must explain how the values were updated given the inputs.
  `,
});

const optimizeScreenQualityFlow = ai.defineFlow(
  {
    name: 'optimizeScreenQualityFlow',
    inputSchema: OptimizeScreenQualityInputSchema,
    outputSchema: OptimizeScreenQualityOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
